#ifndef __VULKAN_FUNCTION_SCOPE_H__
#define __VULKAN_FUNCTION_SCOPE_H__

enum function_scope {
    VULKAN_FUNCTION_SCOPE_DEFAULT = 0,
    VULKAN_FUNCTION_SCOPE_DEVICE,
    VULKAN_FUNCTION_SCOPE_INSTANCE,
    VULKAN_FUNCTION_SCOPE_INVALID,
};

#endif
