#ifndef __VULKAN_PIPELINE_STAGES_DEF_H__
#define __VULKAN_PIPELINE_STAGES_DEF_H__

enum pipeline_stages {
    VULKAN_PIPELINE_STAGE_VERTEX_SHADER = 0,
    VULKAN_PIPELINE_STAGE_FRAGMENT_SHADER,
    VULKAN_PIPELINE_STAGE_VERTEX_INPUT,
    VULKAN_PIPELINE_STAGE_INPUT_ASSEMBLY,
    VULKAN_PIPELINE_STAGE_VIEWPORT,
    VULKAN_PIPELINE_STAGE_DYNAMIC,
    VULKAN_PIPELINE_STAGE_RASTERIZER,
    VULKAN_PIPELINE_STAGE_MULTISAMPLING,
    VULKAN_PIPELINE_STAGE_DEPTH_STENCIL,
    VULKAN_PIPELINE_STAGE_COLOR_BLENDING,
    NUM_VULKAN_PIPELINE_STAGES
};

#endif