#ifndef __VULKAN_QUEUE_TYPES_H__
#define __VULKAN_QUEUE_TYPES_H__

enum device_queue_type {
    VULKAN_DEVICE_QUEUE_TYPE_GRAPHICS,
    VULKAN_DEVICE_QUEUE_TYPE_COMPUTE,
    VULKAN_DEVICE_QUEUE_TYPE_TRANSFER,
    NUM_VULKAN_DEVICE_QUEUE_TYPES,
};

enum device_queue_priority {
    VULKAN_DEVICE_QUEUE_PRIO_LOW,
    VULKAN_DEVICE_QUEUE_PRIO_MIDDLE,
    VULKAN_DEVICE_QUEUE_PRIO_HIGH,
    VULKAN_DEVICE_QUEUE_PRIO_MAX,

    VULKAN_DEVICE_QUEUE_PRIO_DEFAULT = VULKAN_DEVICE_QUEUE_PRIO_MIDDLE,
};


#endif
